// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot;

import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import frc.robot.autonomous.SimpleDrive;
import frc.robot.commands.*;
import frc.robot.subsystems.*;


/**
 * This class is where the bulk of the robot should be declared. Since Command-based is a
 * "declarative" paradigm, very little robot logic should actually be handled in the {@link Robot}
 * periodic methods (other than the scheduler calls). Instead, the structure of the robot (including
 * subsystems, commands, and button mappings) should be declared here.
 */
public class RobotContainer {

  private static final RobotContainer m_robotContainer = new RobotContainer();

  // The robot's subsystems
  public final Drivetrain m_drivetrain = new Drivetrain();
  public final LimeLight m_limelight = new LimeLight();
  public final ShootingSystem m_shootingsystem = new ShootingSystem();
  public final ClimbingSystem m_climbingsystem = new ClimbingSystem();

  // Autonomous Commands

  private final Command m_simpledrive = new SimpleDrive(m_drivetrain);

  // A chooser for autonomous commands
  SendableChooser<Command> m_chooser = new SendableChooser<>();

  /** The container for the robot. Contains subsystems, OI devices, and commands. */
  public RobotContainer() {
    // Smartdashboard Subsystems
    SmartDashboard.putData(m_drivetrain);

    // Configure the button bindings
    configureButtonBindings();

    // Configure default commands
    m_drivetrain.setDefaultCommand(new MecanumDrive(m_drivetrain));
    m_shootingsystem.setDefaultCommand(new BallShooter(m_shootingsystem));
    m_climbingsystem.setDefaultCommand(new ClimbElevator(m_climbingsystem));
   
    // Configure autonomous sendable chooser
    m_chooser.setDefaultOption("Simple Auto Drive", m_simpledrive);

    SmartDashboard.putData("Autonomous Mode", m_chooser);    
  }
  public static RobotContainer getInstance() {
    return m_robotContainer;
  }

  /**
   * Use this method to define your button->command mappings. Buttons can be created by
   * instantiating a {@link GenericHID} or one of its subclasses ({@link
   * edu.wpi.first.wpilibj.Joystick} or {@link XboxController}), and then passing it to a {@link
   * edu.wpi.first.wpilibj2.command.button.JoystickButton}.
   */
  private void configureButtonBindings() {
    // Create some buttons

  }

  /**
   * Use this to pass the autonomous command to the main {@link Robot} class.
   *
   * @return the command to run in autonomous
   */
  public Command getAutonomousCommand() {
    // The selected command will be run in autonomous
    return m_chooser.getSelected();
  }
}
