// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.PWMTalonSRX;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.SpeedControllerGroup;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Subsystem1 extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private PWMTalonSRX speedController2;
private PWMTalonSRX speedController3;
private PWMTalonSRX speedController4;
private PWMTalonSRX speedController5;
private SpeedControllerGroup speedControllerGroup;
private RobotDrive drivetrain;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    /**
    *
    */
    public Subsystem1() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
speedController2 = new PWMTalonSRX(1);
 addChild("Speed Controller 2",speedController2);
 speedController2.setInverted(false);

speedController3 = new PWMTalonSRX(2);
 addChild("Speed Controller 3",speedController3);
 speedController3.setInverted(false);

speedController4 = new PWMTalonSRX(3);
 addChild("Speed Controller 4",speedController4);
 speedController4.setInverted(false);

speedController5 = new PWMTalonSRX(4);
 addChild("Speed Controller 5",speedController5);
 speedController5.setInverted(false);

SpeedControllerGroup speedControllerGroup = new SpeedControllerGroup(speedController2, speedController3 , speedController4 , speedController5);
 addChild("Speed Controller Group",speedControllerGroup);
 

RobotDrive drivetrain = new RobotDrive(speedController2, speedController3,
speedController4, speedController5);
 
 drivetrain.setSafetyEnabled(true);
drivetrain.setExpiration(0.1);
drivetrain.setSensitivity(0.5);
drivetrain.setMaxOutput(1.0);



        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

